version: '3'
services:
  web:
    build: .
    command: gunicorn web.wsgi --bind=0.0.0.0:8000
    env_file:
      - env_file
    volumes:
      - .:/code
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

